services:
  postgres:
    image: postgres:16-alpine
    container_name: dsa-coach-db
    environment:
      POSTGRES_USER: dsa_user
      POSTGRES_PASSWORD: dsa_password
      POSTGRES_DB: dsa_coach
    ports:
      - "5433:5432"
    volumes:
      - dsa_coach_data:/var/lib/postgresql/data

volumes:
  dsa_coach_data: